### ISSUE TITLE
Automatically set the display name to filename (2A)

### ISSUE THREAD

**Issue by NickLaiacona** [performant-software/dm-2#113]
Names of uploaded images have to be manually typed every time, even if the image file is named what you want it to be. This means that large numbers of prenamed images would have to be manually renamed, one by one. (Note: in DM 1.0, filenames were automatically added as the doc name in the upload). Solution: when a file is selected for upload, automatically set the display name for the label in DM as its filename.

**Comment by blms** [comment]
Closed by #308.
