### ISSUE TITLE
Text window can become misaligned

### ISSUE THREAD

**Issue by SteveMarvin** [performant-software/dm-2#125]
When multiple copies of the same doc are open, adding a line return to an empty line will cause the text editor window to become misaligned. 
![Screen Shot 2019-01-08 at 4.48.26 PM.png](https://images.zenhubusercontent.com/570d1074bf93871ccd994cd2/859ba089-74dc-48c3-841f-b51bf99ff553)

**Comment by MartinFoys** [comment]
Resolved with #326
