### ISSUE TITLE
cannot move folders and objects out of folders and back to the root level of the TOC

### ISSUE THREAD

**Issue by SteveMarvin** [performant-software/dm-2#174]
## Steps to test

[On staging](https://dm-2-staging.herokuapp.com/),
- Create a subfolder inside of another folder
- Move that subfolder out of the folder into the root of the project
- Try the same with a doubly nested folder
- Try moving subfolders from one folder to another as well

---

From Martin: Students have reported being unable to move folders they've accidentally moved inside another folder back out again. I set up an project to test this, and it's verified. It's here: 
https://uw.digitalmappa.org/44
There are two folders inside another folder. I moved those folders inside the other folder, and now cannot move them back out again!

**Comment by SteveMarvin** [comment]
This is now resolved. Note, however, that one must see the horizontal insertion line before dropping or it will not work. This can require some slightly fine maneuvering of the cursor. It does work, however.

**Comment by blms** [comment]
Reopening as this was fixed for objects only, but not folders.

**Comment by blms** [comment]
Closing per acceptance in QA
