### ISSUE TITLE
highlight extension bug

### ISSUE THREAD

**Issue by SteveMarvin** [performant-software/dm-2#175]
Found another highlight making bug - see the attached video. 

I attempt to make a highlight of a certain (extended) string of text. When the highlight is made, it actually seems to extend beyond the string for several characters on both sides (note how once the highlight is made, more of the string is then shown as selected than actually colored). Subsequently, any attempt to type within the text that falls within this "extended" highlight results in an alert that warns against deleting multiple highlights (even though only one highlight was made). 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/18423533/54637174-5e3dcb00-4a5e-11e9-9b7e-f089c7337809.gif)

**Comment by blms** [comment]
Fixed by a3a05a46ee8c852a092e2eb077e860e4c6743fe5 in #369. Basically the solution was to call `editorView.focus()` after every transaction.
