### ISSUE TITLE
Uploading cropped images can display as doubled - sideways has also occurred (3L)

### ISSUE THREAD

**Issue by MartinFoys** [performant-software/dm-2#195]
If you crop an image in Preview on a Mac, but don't CMD-S save the image, subsequently the image displays as cropped, but I think retains some version of uncropped image in its file. 

Uploading this kind of image to DM 2.0 results  a doubled image displaying. 

But cropping the same image in Preview and then CMD-S saving the file discards the cropped data, and uploading this image does not result in a doubled image. 

Sideways image display has also occurred on some uploads.

**Comment by NickLaiacona** [comment]
this appears to be related: https://github.com/openseadragon/openseadragon/issues/1362

**Comment by SteveMarvin** [comment]
I have had success in recompressing the jpeg. Resizing up and then back down works, as does exporting and choosing a new compression level.

**Comment by blms** [comment]
Accidental close.

**Comment by MartinFoys** [comment]
Dammit - I got excited 😄

**Comment by blms** [comment]
Hi @MartinFoys, there is a fix for this live on staging now. Steve isn't able to test without access to a Mac; can you test some images known to be problematic and see if it's still occurring?

**Comment by MartinFoys** [comment]
Good news and bad news - the fix seems to take care of the doubling issue, but on upload it appears to crash the project. See video. On reload the image is fine and NOT doubled, though!

https://user-images.githubusercontent.com/45047191/128528255-c6f9d020-e3a8-46d9-bde2-3e0f0efdfe85.mov

**Comment by blms** [comment]
@MartinFoys Great! Working on a fix for that now, Steve filed it under #343.
