### ISSUE TITLE
Copy and pasting text with highlights issues (3R)

### ISSUE THREAD

**Issue by MartinFoys** [performant-software/dm-2#198]
Copy and pasting text that has highlights is designed to carry links with the paste, but this only works infrequently. Additionally, deleting a highlight from a paste, where the copied highlight has links, then also deletes those links from the original highlight that was copied (but not deleted). This has also been communicated to Nick.

**Comment by blms** [comment]
Hi @MartinFoys, I can't replicate this issue—can you check if it's still happening? If so, can you provide screenshots/video of the bug? Thanks!

**Comment by MartinFoys** [comment]
VERRRRRY Interesting!  I literally encountered this issue last week in the older 2.0 instance, but now cannot replicate in staging. Is it possible that the refinements you made to synching display of text docs could have fixed this? I will play around more and see if I can make it happen in production instead. But it was a super common issue - you'd paste some text with multiple highlights, and only the first one would work in the pasted text, while others would be all messed up or not work at all.  Hmmmm!

**Comment by blms** [comment]
@MartinFoys Glad to hear it seems to be resolved, at least in staging. I think it may have been related to a bug in the duplicate highlights function on the backend that was causing malformed highlights all over the place, which I fixed in #320. If I'm right about that, then it should also be fixed in production!

**Comment by MartinFoys** [comment]
Okay - here you go - weird stuff replicated in staging:

Steps: 
Opened Glossary (did not check out)
Copied Text with highlights and links from Glossary into a brand new doc
New Doc now has the active highlights, but the link back to the original doc now too, sometimes in multiples, and sometimes with the color reverting to yellow (which is I think the default color - used to see that color reversion in corrupted link pastes alot). 

Compare in the image how the links in source and copy are different. 


![image](https://user-images.githubusercontent.com/45047191/128210355-5555830e-c2fa-485f-b095-51c6e52d1fa6.png)

**Comment by MartinFoys** [comment]
Here's another example of recursive linking happening from the same process of pasting:

![image](https://user-images.githubusercontent.com/45047191/128212223-bac98dc7-3060-4aed-a992-28ff54ec327a.png)

**Comment by MartinFoys** [comment]
Note - though - these issues above are different than what I used to encounter. Usually, you'd try to paste a bunch of texts with highlights and (maybe) the first highlight would still work, and then all the others would be crazy - like the color would be yellow as default and the highlight title was a string of text from the text of the doc that was surrounding the highlight, and none of the links would carry over into the pasted highlights, or most of the highlights would appear but would be "dead" - i.e. you couldn't click on them to do anything. 

None of that seems to be manifesting in the new versions, as far as I can tell, but this stuff above now is.
