### ISSUE TITLE
Selected text display disappears when the text toolbar is clicked on (3O)

### ISSUE THREAD

**Issue by MartinFoys** [performant-software/dm-2#202]
Selected text display disappears when the text toolbar is clicked on, even though the text remains selected and active (i.e. selected text display should not disappear in these cases).

**Comment by jamiefolsom** [comment]
Hey @blms: Is this the same as: "When text is selected (is highlighted in blue) and a setting is applied to the text (e.g., bold, italic) the selection highlight disappears"? That's `3O` from the budgeted list.

**Comment by MartinFoys** [comment]
Yep - these should be the same thing.
