### ISSUE TITLE
Move “back to project list” arrow out of the collapsible TOC and up to the top right of the black bar. (2B)

### ISSUE THREAD

**Issue by MartinFoys** [performant-software/dm-2#207]
Move “back to project list” arrow out of the collapsible TOC and up to the top right of the black bar. (as discussed with Nick)

It's odd that the “back to project list” button is not on the top back menu bar, and so always available. 
Additionally, users sometimes confuse this <-- arrow button as being for collapsing the TOC frame, which then takes them completely out of the project and closes all of their workspace, which is a real bummer.

**Comment by blms** [comment]
Closed by #305.
