### ISSUE TITLE
Mechanism for distinguishing the targeted highlight that is opened from a link (1C)

### ISSUE THREAD

**Issue by MartinFoys** [performant-software/dm-2#209]
DM 1.0 had a mechanism for distinguishing the targeted highlight that is opened from a link, so that is may be easily seen (in images, it was the only highlight visible, in texts, it was blue instead of the the usual yellow)

In DM 2.0, it'd be great if the opened, targeted highlight was similarly distinguished, maybe by a some kind of border, glow, or the like.

**Comment by blms** [comment]
Closed by #312.
