### ISSUE TITLE
Import SIMS projects

### ISSUE THREAD

**Issue by NickLaiacona** [performant-software/dm-2#227]
Import the following projects from sims.digitalmappa.org:

* Cartas Ejecutorias
* Digital Grave
* Four Anglo Carolingian Mini Editions from Cotton Vespasian_MS_D
* La Chronique Anonyme Universelle
* Little Gidding Harmony Houghton
* Little Gidding Acta Apostolorum British_Library
* Old English and Anglo Latin Belltokens
* Virtual Mappa

**Comment by NickLaiacona** [comment]
In La Chronique Anonyme Universelle, the geneology chart highlights weren't aligned with the chart. Fixed.

**Comment by SteveMarvin** [comment]
Highlights are now alinged
