### ISSUE TITLE
Closing one instance of a doc opened multiple times closes a different instance

### ISSUE THREAD

**Issue by MartinFoys** [performant-software/dm-2#230]
1. Open up two instances of the same doc. Scroll around in the first, and set the color to a different color (here, blue) as a marker for which one is which:

![image](https://user-images.githubusercontent.com/45047191/67883474-2d546700-fb12-11e9-802f-1ccdc84e8323.png)

2. Close the SECOND instance of the doc (with yellow color still selected):

![image](https://user-images.githubusercontent.com/45047191/67883557-4bba6280-fb12-11e9-930f-908efdbb0163.png)

3. Result: Second instance doesn't close - the FIRST one does! Instance with blue color is closed, instance with yellow remains open. 

![image](https://user-images.githubusercontent.com/45047191/67883724-963bdf00-fb12-11e9-8155-64bd130be0d2.png)

**Comment by SteveMarvin** [comment]
This is no longer happening
