### ISSUE TITLE
Loading images via external URL seems to be broken

### ISSUE THREAD

**Issue by MartinFoys** [performant-software/dm-2#235]
Have tested on a number of urls, all to jpg images with easy urls online. Each attempt does not display an image, though the thumbnail does load. See attached image, which attempted to load the following: https://d4804za1f1gw.cloudfront.net/wp-content/uploads/sites/30/2019/01/14013139/06_01_015470.jpg

Munich reports a similar issue with their test DM2 site, noting the following error is returned:  Unable to open object: Error loading image at http://localhost:3001/rails/[...]

![image](https://user-images.githubusercontent.com/45047191/68506393-2b378a00-022f-11ea-8fe6-7c2ea8253073.png)

**Comment by SteveMarvin** [comment]
This is working properly
