### ISSUE TITLE
• Having two instances of the same doc open is an issue when making highlights.

### ISSUE THREAD

**Issue by MartinFoys** [performant-software/dm-2#237]
• Having two instances of the same doc open and next to each other and then making a highlight on one of them causes one of the docs to freak out and become misaligned.

ETA: same issue occurs when attempting to type in one of the docs - that doc then becomes misaligned as below. 

Here's what it looks like after - note how the frame of the left instance is all messed up now.

![image](https://user-images.githubusercontent.com/45047191/68537050-8b0f5d00-0323-11ea-9250-4c6fbe6c2784.png)

**Comment by SteveMarvin** [comment]
The specifics of this highlighting issue have been corrected, but a related problem to do with typing has been exacerbated. That bug has been written up separately to allow this one to be closed.
