### ISSUE TITLE
Typing in a duplicate window causes misalignment of focused window (3K)

### ISSUE THREAD

**Issue by SteveMarvin** [performant-software/dm-2#241]
Typing causes the window to shift out of alignment. It can also cause the window to jump to the bottom of the document when applying formatting such as bold or italics. 

![Screen Shot 2019-11-26 at 12.48.05 PM.png](https://images.zenhubusercontent.com/570d1074bf93871ccd994cd2/d1b3edec-3f23-40cd-8c2a-c2f666e62b57)

**Comment by blms** [comment]
Cannot replicate—possibly fixed by #320?
