### ISSUE TITLE
Null user on checked out documents

### ISSUE THREAD

**Issue by dleadbetter** [performant-software/dm-2#269]
Occasionally when editing a document, the document status will display that the document is checked out by "null". This leaves the document in a state where it cannot be checked back in, or edited.

![null-user.png](https://images.zenhubusercontent.com/5e1cb7e20277183b4b37158f/f7e885c6-c248-470f-bec2-fdbcfeef1cd0)

**Comment by MartinFoys** [comment]
Fixed earlier this year.
