### ISSUE TITLE
Additional Text Editing Features (1B)

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/dm-2#289]
Improved text editing features, implementation of expanded text toolbox that can accommodate margins, columns, tables, text colors, font sizes and types, strikethrough text, hard return line inserts, tab spacing/indentation and line spacing.

Includes bugfixes 3I ([underline keyboard shortcut](https://github.com/performant-software/dm-2/issues/201)) & 3O ([selection highlight disappears](https://github.com/performant-software/dm-2/issues/202))

- [ ] margins: as in for the entire text doc? ideally for whole document, and also for blocks.
- [ ] columns: client ok with using tables (where you can make the border the background color)
- [ ] tables: supported by prosemirror module
- [x] hard return (lf) line insert
- [ ] tab spacing/indentation: be able to use tab key?
- [ ] line spacing: for whole doc or specific selections?
- [ ] Colors: [ basic color palette/picker ]
- [x] Strikethrough
- [x] Font sizes (pt units, etc)
- [x] Font selection [ families: serif, sans, fixed width ]
- [x] Blockquote, with indent
- [x] Key mappings 
```js
{ 
  cmd-i: italic, 
  cmd-b: bold, 
  cmd-u: underline, 
  cmd-shift-x: strikethrough
  cmd-c: copy
  cmd-v: paste
  cmd-x: cut
}
```
Notes / future ideas
- Don't need paragraph/header
- Martin uses google docs for some things.
- Other alphabets? [Japanese has been requested]

**Comment by blms** [comment]
Hi @MartinFoys,
>  hard return (lf) line insert

This is actually already possible. When you press Enter in a document you are inserting a paragraph break (hard return). When you press Shift-Enter or Command-Enter, you are inserting a line break (soft return). However, currently all paragraph spacing is set to 0, so you wouldn't be able to tell the difference between a paragraph break and a line break. 

Did you want there to be some paragraph spacing applied by default to make these visually distinct? Or did this mean something else?

(I also at first misunderstood this to mean horizontal rule, which I've added on my branch—not yet published—but can remove if desired.)

**Comment by MartinFoys** [comment]
Ah - no it is a graphic line insert - the <HR> in html, I think?

This:

![image](https://user-images.githubusercontent.com/45047191/129105105-92a0b089-6674-481e-b861-1f8c3afa8099.png)

**Comment by blms** [comment]
@MartinFoys Ah, great! That's the horizontal rule, I've added it on my branch so it'll be added soon. :)

**Comment by blms** [comment]
Closing to separate: #66, #67, #69, #184, #360, #361, #362, #363, #364, #365
