### ISSUE TITLE
Add two more/new color options to img/text highlights (1F)

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/dm-2#290]
Expand color palette options on images and text highlights from 8 colors to 10 (add light blue and neon light green options).

**Comment by blms** [comment]
<img width="291" alt="Screen Shot 2021-07-12 at 3 52 30 PM" src="https://user-images.githubusercontent.com/7234006/125347670-32c70480-e329-11eb-9fed-0adef6dde7ef.png">

@jamiefolsom Do these colors seem differentiated enough / fit the aesthetic?

Here's a little more toned-down but maybe a bit harder to differentiate:

<img width="296" alt="Screen Shot 2021-07-12 at 3 58 53 PM" src="https://user-images.githubusercontent.com/7234006/125348401-298a6780-e32a-11eb-8364-30320afec7a9.png">

**Comment by jamiefolsom** [comment]
I like the more intense ones. Easier to tell apart, as you say! Raises the question of how accessible this feature is, come to think of it.

**Comment by blms** [comment]
Good point. I just ran it under Color Oracle and got the following:

**Comment by blms** [comment]
Closed by #300
