### ISSUE TITLE
Reorder links/annotations in the highlight pop-up menu (2I)

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/dm-2#292]
Reorder links/annotations in the highlight pop-up menu.

**Comment by blms** [comment]
I believe this may require a change to the DB schema.

<details>
<summary>My own notation thinking through the issue/solution, feel free to skim/skip.</summary>

The way it currently works is that a new Link is created in the DB when you drop a Document (which could be image, text, annotation) onto the Highlight's popup menu. That Link has its `linkable_a_id` as the Highlight's ID, and its `linkable_b_id` as the Document's ID.

Every Linkable object, which includes Highlights, knows a list of its `a_links` and `b_links`, in other words, Link objects in which its ID appears as `linkable_a_id` or `linkable_b_id`. When you open the popup menu, the Highlight's `a_links` list is sent back to the frontend (via a Linkable method `links_to`, passed as HighlightSerializer param), and these links appear as the link list.

`a_links` is not ordered in any particular way; in fact, it only exists in Rails as an ActiveRecord association, not in the DB schema, and its order is determined by Rails when it pulls all the associated Links with `linkable_a_id` matching the Highlight's `id`. Thus, ordering it would require a change to the DB schema, such that a Highlight also knows and persists the intended order for its `a_links` list.

I think this could be accomplished by giving each Highlight a dictionary with each Link's `id` as its key and `order` as its value. It must be ensured that this list contains the same Links as `a_links`.

(How it works for TOC: The TOC order is actually stored by each Document and DocumentFolder. So the TOC only knows that order by looking at each Document and DocumentFolder whose parent is the Project—or a DocumentFolder within the Project.)
</details>

I would need to write and run a migration to migrate all existing data to ensure compatibility. This migration will preserve every list in its current order, and then my frontend code will allow any ordering to be changed manually in the UI.

@jamiefolsom Do we have a certain process for ensuring backup and completing data migrations for partnered users in such situations? Is it something that anyone else should be alerted to? Feel free to Slack DM to discuss these aspects, but thought it is helpful to document my thinking here.

**Comment by blms** [comment]
Closed by #313.
