### ISSUE TITLE
Toggle text highlights on and off with "eye"icon (2K)

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/dm-2#293]
Toggle text highlights on and off with "eye" icon.

**Comment by blms** [comment]
This actually also uncovered a bug: when a user has hidden highlights for an image, and "checks out" the document to edit it, those highlights still will not be visible. Basically the toggle just has to be reset when "check out" is clicked.

**Comment by blms** [comment]
Closed by #303.
