### ISSUE TITLE
Toggle text highlights per-instance instead of per-document

### ISSUE THREAD

**Issue by blms** [performant-software/dm-2#304]
After #303, If more than one instance is open of the same text document, hiding/unhiding highlights on that document will apply to all open instances. This is because unlike images, text document state is controlled by document ID and not instance key.

Work has begun to change that scheme in the [blms/highlights-by-key](https://github.com/performant-software/dm-2/tree/blms/highlights-by-key) branch. This requires more work, as changing text document state to refer to instance key has a cascading effect. Now all other state must be properly synced across multiple instances of the same document. For example: as that branch exists now, if two instances of the same doc are open and "checked out", the second instance would no longer reflect edits made to the first, even when the user "checks in" those changes.

**Comment by jamiefolsom** [comment]
We should confirm whether this is the intended behavior with @NickLaiacona -- changes to this could run counter to user expectations if so.

**Comment by blms** [comment]
@jamiefolsom Thinking about this further, that may not be necessary, since we have the existing example of image document highlight toggling—which is per-instance rather than per-document. So we can just treat #303 as a stopgap that implements the feature per-document, and treat this issue as a push to make it more consistent with image highlight toggling.

Then the rest of the functionality will remain per-document so as not to produce any unexpected behavior for users.
