### ISSUE TITLE
Cannot target different highlights on different instances of a text document (1C)

### ISSUE THREAD

**Issue by blms** [performant-software/dm-2#317]
Two issues with having more than one instance of the same text document open:
1. They will both scroll to the most recently targeted highlight
2. They will both only indicate (blue glow) the most recently targeted highlight

https://user-images.githubusercontent.com/7234006/127159285-448ccda1-dc3f-42de-bc49-8d4688162977.mov

**Comment by blms** [comment]
This relates to a long-standing issue with text documents, which I originally noted in #304.

Namely, everything related to contents of text documents is kept track of on a "per-document" rather than "per-instance" basis. I believe this is primarily for the sake of editing. When you have two instances of the same image open, the only thing you can edit is highlights. But when you have two instances of the same text document open, you can actually change the text content. So, I think the idea was that all instances of the same text document should be synchronized so that edits made to one will always be reflected in the others.

It is clear that the priority should be for the "viewer" rather than the "editor". Still, these will have to be synchronized close to realtime to avoid conflicts between two instances of the same text document being opened and edited at once.

Fixing this issue will be a rather large overhaul of the way text documents are dealt with, and may be a significant time investment.

**Comment by MartinFoys** [comment]
yes, I agree - let's fix it. There's also a related 2.0 bug fix issue (see #241) for this already budgeted with 6 hours allocated, so that's even more time available: 

![image](https://user-images.githubusercontent.com/45047191/127168231-ad3b4898-5155-4fa5-b403-4cdd33212e0a.png)
