### ISSUE TITLE
Two instances of same doc become misaligned on highlight (3K)

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/dm-2#326]

**Comment by blms** [comment]
Cannot replicate—possibly fixed by #320?

**Comment by blms** [comment]
Hi @MartinFoys, do you know if this is the same behavior as #241 or is this referring to something else? If you have screenshots or other comments on this issue that would also be helpful.

**Comment by MartinFoys** [comment]
Hey @blms - this is the same behavior - it appears to be resolved by your previous fixes - just tried to make it happen. 

~ M
