### ISSUE TITLE
update installation notes at readme file RE: node.js

### ISSUE THREAD

**Issue by maxgray20** [performant-software/dm-2#338]
Hi @jamiefolsom and everyone:
We successfully installed at Marquette University in Milwaukee. We used the DM2 v0.4.1 release, but swapped out the release gem files for @hawkpf's gem files, and followed his advice RE: the index files at issues #272 and #287. We also needed to activate the node.js buildpack at our heroku application settings. We assumed it was activated by a json file somewhere in the application but it wasn't. So we needed to activate at our heroku application settings. The installation notes should include this requirement.
Thank you!
Max

**Comment by MartinFoys** [comment]
@blms - Can we have the new gem files and the advice  provided at #277 and #287 added as a priority action item so people can get DM up and running without these issues? I already added the bit about activating the node.js buildpack in the Heroku application settings, but was unsure if I put it in the best place in the README.

**Comment by blms** [comment]
@MartinFoys Thanks for adding to the Readme. We can definitely prioritize the Ruby upgrade.

I'm not sure about the `index.html` issue—seems like that didn't actually help per https://github.com/performant-software/dm-2/issues/272#issuecomment-889992185. Maybe that piece was resolved by activating the Node.js buildpack? @maxgray20  can you confirm that the `index.html` did not resolve the `ActionController::RoutingError`? I did not have that issue with my local install.

The Ruby upgrade probably also isn't as pressing as it seems; it is only deprecated by Heroku starting in 2023. We can specify that users should use the `heroku-18` stack in the meantime. Though #287 says it is not supported, it actually is supported through April 30th, 2023, but it just has to be explicitly chosen by the user.

**Comment by MartinFoys** [comment]
@blms - okay - great, thanks - yeah, anythng that can be added to the README to quickly spell out these issues and what should be done would be great. With the new release including image layers, there is a chance that more people will want to install, and we want to avoid a pile-up of installation problems if possible!

**Comment by blms** [comment]
@MartinFoys Just updated the README, it should be all set for now until April 2023, unless there are still issues with `index.html` that only show up during a Heroku install.

**Comment by maxgray20** [comment]
Hi @MartinFoys and @blms --
Yes, I think what was critical for our install was the updated gem files and node.js buildpack activation. But we'd need to reinstall minus following advice RE: the index files to confirm for certain. Thanks all! Max

**Comment by blms** [comment]
Thanks much @maxgray20! In that case, we'll close this for now and deal with #287 separately.

**Comment by hawkpf** [comment]
I appologize that I have not been responsive but I'm swamped at work and after work.  I'll see if I can do a git pull --rebase as requested for my PR https://github.com/performant-software/dm-2/pull/287 some time this week.

**Comment by blms** [comment]
No problem @hawkpf. I'll make a comment there.
