### ISSUE TITLE
Scroll moves toolbar offscreen

### ISSUE THREAD

**Issue by SteveMarvin** [performant-software/dm-2#378]
When a single document is open, if the user scrolls down aggressively, it will grab the entire window array and scroll it up, moving the top of the current document offscreen and obscuring the toolbar. This is far too easy to do when working with the bottom part of a document window.

![image.png](https://images.zenhubusercontent.com/570d1074bf93871ccd994cd2/dafd56bd-53d0-477d-81d2-ea9e3320dd00)

**Comment by jamiefolsom** [comment]
Closed per Martin.
