### ISSUE TITLE
Batch upload issue - full list of current folders does not display

### ISSUE THREAD

**Issue by MartinFoys** [performant-software/dm-2#446]
Just caught something I hadn't noticed before - there seems to be a hard limit on the existing folders you can select from when batch uploading - on production (https://uw.digitalmappa.org/58) - it only shows the first few of many, with no scroll option to select one further down in the list. Earlier I thought I saw a scroll bar, but even then it was still limited:
![image](https://user-images.githubusercontent.com/45047191/135726229-43013d79-ff4b-4289-b926-6eb7a1d96d6f.png)
On Staging (https://dm-2-staging.herokuapp.com/58) it's even weirder, only offering one folder out of many, and not even the first one:
![image](https://user-images.githubusercontent.com/45047191/135726240-35528672-ba65-40cb-92bb-e41e0d4ed647.png)

**Comment by SteveMarvin** [comment]
This looks good
