### ISSUE TITLE
Text editor text loses color on paste

### ISSUE THREAD

**Issue by blms** [performant-software/dm-2#452]
## Testing instructions

- Visit https://dm-2-staging.herokuapp.com/ and log in
- Open or create a project, open or create a new text document
- Write some text with different colors applied in various places
- [ ] Copy that text and paste it, and confirm the colors are correctly copy/pasted

**Comment by MartinFoys** [comment]
Adding a note here - the migration of DM 2.0 projects to 2.1 also appears to have stripped out the color formatting for text that was there previously. So is likely a related issue.
