### ISSUE TITLE
Link to an individual document or documents

### ISSUE THREAD

**Issue by blms** [performant-software/dm-2#531]
Allow a user to create a link to a document inside of a project, instead of just the entire project.

## testing notes

On the [staging site](https://dm-2-staging.herokuapp.com/):
- [x] Open some documents in a project. The browser's URL should change to include `?document=`, `&document=` followed by document IDs.
  - [x] Copy the URL after you've opened some documents, and open it in a new window. The opened documents should reopen in the new window.
- [x] Each document should have a share icon on its header, in the top right corner
  - [x] Clicking this icon should bring up a URL and a "copy link" button
  - [x] Clicking either should copy the URL for just that document to the clipboard
- Create an annotation on a document (click on highlight --> "Add annotation") and use its share button to get its URL
  - [x] Opening the URL for just the annotation in a new window should also open up its parent document
- Create a document within nested subfolders and use its share button to get its URL
  - [x] Opening the URL for this document should also open the subfolders in the table of contents

**Comment by SteveMarvin** [comment]
Everything works like a charm!
