### ISSUE TITLE
Current line segment should be visible during drawing

### ISSUE THREAD

**Issue by SteveMarvin** [performant-software/dm-2#61]
In DM 1.0, the line tool shows the next segment in the line as visible before you click on its landing point. This is extremely useful as it allows the user to precisely place the segment where they want it, before they click to finalize it. In 2.0, the segment is invisible before the click, which makes precise placement difficult. Can we have the line tool work more like it does in 1.0?

**Comment by blms** [comment]
Closed by #291.
